-- Auth própria do módulo contábil: store de usuários "contador" para o app standalone.
-- Não afeta o fluxo de eventos do ERP (que segue via X-API-Key / service-to-service).
CREATE TABLE contabil.contador (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(160) NOT NULL,
    nome        VARCHAR(160) NOT NULL,
    senha_hash  VARCHAR(120) NOT NULL,
    ativo       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_contador_email ON contabil.contador (lower(email));
