-- V18: registro NATIVO do pagamento do DAS (Simples Nacional) no módulo contábil.
-- Torna o módulo a AUTORIDADE única do pagamento por competência: tanto o app standalone
-- quanto o ERP (que passa a delegar) gravam aqui. O UNIQUE(competencia) é a trava que
-- impede baixar o mesmo passivo (2.1.3.01) em dobro, venha de onde vier.
CREATE TABLE contabil.pagamento_das (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competencia       VARCHAR(7)  NOT NULL,       -- AAAA-MM
    valor_centavos    BIGINT      NOT NULL,
    data_pagamento    DATE        NOT NULL,
    conta_liquidacao  VARCHAR(20) NOT NULL,       -- 1.1.1.01 (Caixa) ou 1.1.1.02 (Bancos)
    lancamento_id     BIGINT,                     -- lançamento gerado (via roteiro das.pago)
    evento_id         UUID,                       -- evento idempotente que originou o lançamento
    origem            VARCHAR(20) NOT NULL DEFAULT 'app',   -- 'app' (contador) | 'erp' (Odonto)
    created_at        TIMESTAMP   NOT NULL DEFAULT now()
);

-- Trava de idempotência compartilhada: uma competência só é paga uma vez (app OU erp).
CREATE UNIQUE INDEX ux_pagamento_das_competencia ON contabil.pagamento_das (competencia);
