-- V9: atendente -- auth PROPRIA do modulo whatsapp (app standalone do atendente).
--
-- MOTIVACAO: ate a V8 o api-whatsapp so tinha auth service-to-service (X-API-Key,
-- consumida pelo ERP) e o webhook publico (HMAC). O app web do atendente (front
-- Angular servido pelo proprio jar em Phase seguinte) precisa de login proprio: esta
-- tabela guarda o usuario "atendente", autenticado localmente (BCrypt) e emitindo JWT.
-- NAO afeta o fluxo de eventos do ERP (X-API-Key) nem o webhook (HMAC) — e aditiva.
--
-- Espelha whatsapp.config_meta / contabil.contador na disciplina de portabilidade
-- (mesma logica da V1..V8): tipos e constraints suportados por PostgreSQL 15 E H2 2.x
-- modo PostgreSQL. IDENTITY (GENERATED BY DEFAULT) funciona nos dois; a entity
-- Atendente usa @GeneratedValue(strategy = IDENTITY). senha_hash com folga para o
-- hash BCrypt (60 chars).
--
-- UNIQUE de email: coluna com UNIQUE simples (como telefone na V1 / wamid na V2) —
-- H2 modo PostgreSQL NAO suporta indice funcional 'CREATE UNIQUE INDEX (lower(email))'
-- (diferente da contabil.contador, cujos testes usam Postgres real via Testcontainers).
-- A unicidade case-insensitive fica garantida pela aplicacao: o e-mail e sempre
-- persistido em minusculas (AtendenteSeeder) e as buscas usam lower() (AtendenteRepository).

CREATE TABLE whatsapp.atendente (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(160) NOT NULL UNIQUE,
    nome        VARCHAR(160) NOT NULL,
    senha_hash  VARCHAR(120) NOT NULL,
    ativo       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
);
